### PR TITLE
Remove python 3.5 from the tests on travis

### PR DESCRIPTION
**Pull request by matthewturk**
Python 3.5 doesn't work with current pytest-cov.

### CODE REVIEW

**Comment by matthewturk** [comment]
The real issue seems to be the version of yt we are installing.

**Comment by matthewturk** [comment]
One option [identified here](https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repo-as-a-dependency) is to use this in our `install_requires`:

```
'ExampleRepo @ git+ssh://git@github.com/example_organization/ExampleRepo.git#egg=ExampleRepo-0.1'
```

until there is a new release of yt.

**Comment by munkm** [comment]
can't we test for yt < 3.6 until 3.6.1 comes out?

**Comment by matthewturk** [comment]
I genuinely don't know.

**Comment by munkm** [comment]
ok i pinned matplotlib for our tests instead. We can unpin later.

**Pull request merged**
